[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[metadata]
name = "SVInsight"
version = "0.3.2"
description = "Create social vulnerabilty index"
readme = "long_desc.md"
author = "Matthew Preisser, Paola Passalacqua, R. Patrick Bixler"
author_email = "mattpreisser@gmail.com"
license = "MIT"
license_file = "LICENSE.txt"
url = "https://github.com/mdp0023/SVInsight"

[options]
python_requires = ">=3.9"
install_requires = [
    "census",
    "factor_analyzer",
    "geopandas",
    "numpy",
    "pandas",
    "PyYAML",
    "scikit_learn",
    "openpyxl",
    "matplotlib"
]

[tool.setuptools]
package-dir = {"" = "SVInsight"}

[options.extras_require]
docs = ["sphinx"]

[metadata.urls]
Documentation = "https://mdp0023.github.io/SVInsight/"