[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SVInsight"
version = "0.2.9"
dependencies = [
    "census",
    "factor_analyzer",
    "geopandas",
    "numpy",
    "pandas",
    "PyYAML",
    "scikit_learn",
    "openpyxl",
    "matplotlib"
]
requires-python = ">=3.8"
authors = [
  {name = "Matthew Preisser", email = "mattpreisser@gmail.com"},
]
description = "Create social vulnerabilty index"
readme = "README.rst"
license = {file = "LICENSE.txt"}
keywords = ["SVI"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python"
]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://readthedocs.org"


