name: compatability_testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        dependencies: ["latest", "minimum"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        if [ "${{ matrix.dependencies }}" = "latest" ]; then
          pip install .
        else
          pip install .[minimum]
        fi
    - name: Test with pytest
      env:
          API_KEY: ${{ secrets.API_KEY }}
      run: |
        pip install pytest
        pytest